# Pickaxe 3x3 - uses bStats to collect anonymous statistics about the server's usage.

language: en # This function is responsible for translating the message in your plugin. (en/ru)

legacy: false # This function is responsible for 3 by 3 by 3 cube blocks, that is, what was before plugin version 10.5.5

lore: # This function corresponds to the description of the pickaxe when it is given to the player.
  enabled: false
  text:
    - ""
    - " &b&l▫ &fPickaxe breaks 3 by 3 blocks."
    - " &b&l▫ &fThanks for downloading the plugin!"
    - " &b&l▫ &fEnjoy using it."

disabled_worlds: # This function is responsible for disabling the world where the pickaxe will not work.
  - example_world

enchantments: # This function is responsible for adding enchantments to the pickaxe.
  enabled: false
  list:
    - enchantment: minecraft:efficiency
      level: 5
    - enchantment: minecraft:unbreaking
      level: 3

unbreakable_pickaxe: false # This function is responsible for disabling pickaxe breaking.

regions: # Setting up for regions in the WorldGuard plugin.
  enabled: true # [!] If you disable this feature on the server, the pickaxe will break in the regions.
  list: # Here you can add regions in which it will be possible to break if they are intersected by another region.
    - region1
    - region2

breakable_fast: # This function is responsible for the strength of the pickaxe. "true" - the pickaxe loses 9% of its strength when broken.
  enabled: false

unbreakable_blocks: # This function is responsible for blocks that a pickaxe cannot break.
  enable: false # true – take into account the type list, false – ignore.
  type: # additional unbreakable blocks.
    - OBSIDIAN
    - ANCIENT_DEBRIS

use_unbreaking: false # Defines whether the pickaxe respects the Unbreaking enchantment. Thanks to @EpicJosch for the idea and implementation.

gentle_mode: # When the durability drops below the threshold (%), the pickaxe loses its ability to break 3x3 and works as a normal one.
  enabled: false # [!] This is a new feature, if you have any performance issues, please post on the forum.
  threshold: 10 # Threshold as a percentage of maximum strength (1-100).

  # Do you still have questions about the plugin, or have you found a bug? Be sure to write reviews on the plugin page.