name: Pickaxe3x3
version: 1.9.0
main: ru.sht3nd.pickaxe3x3api.Pickaxe3x3Api
api-version: '1.13'
description: Plugin for giving 3x3 diamond and netherite pickaxes.
author: Sht3nd
softdepend: [WorldGuard, WorldEdit]
commands:
  pickaxe3x3:
    description: Get a 3x3 pickaxe.
    usage: /pickaxe3x3 <diamond|netherite> <player>
    permission: pickaxe3x3.admin
permissions:
  pickaxe3x3.admin:
    description: Allows the use of the /pickaxe3x3 command.
    default: op